server {
    listen 80;

    # 1. Отдаем React фронтенд
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html; # Чтобы работали роуты React
    }

    # 2. Проксируем запросы к бэкенду
    location /api/ {
        proxy_pass http://backend:8080/api/; # 'backend' - имя контейнера бэка
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}